# Generated by Django 5.2.5 on 2025-08-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Razón Social')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección Matriz')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('firma_electronica', models.FileField(blank=True, null=True, upload_to='firmas/', verbose_name='Archivo de Firma (.p12)')),
                ('clave_firma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave de la Firma')),
                ('ambiente_sri', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('activa', models.BooleanField(default=True, verbose_name='Suscripción Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC/Cédula')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Razón Social')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], max_length=1)),
                ('tipo_emision', models.CharField(default='1', max_length=1)),
                ('secuencial', models.CharField(editable=False, max_length=9)),
                ('clave_acceso', models.CharField(editable=False, max_length=49, unique=True)),
                ('fecha_emision', models.DateField()),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_impuestos', models.JSONField()),
                ('propina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='DOLAR', max_length=15)),
                ('pagos', models.JSONField()),
                ('estado_sri', models.CharField(choices=[('P', 'Procesando'), ('A', 'Autorizada'), ('R', 'Rechazada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('xml_generado', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos', models.JSONField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio Unitario de Venta')),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo Unitario')),
                ('stock', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('maneja_iva', models.BooleanField(default=True, verbose_name='Grava IVA')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada/Compra'), ('S', 'Salida/Venta'), ('AJ_E', 'Ajuste de Entrada'), ('AJ_S', 'Ajuste de Salida')], max_length=4)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.compradetalle')),
                ('detalle_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facturadetalle')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_establecimiento', models.CharField(max_length=3, verbose_name='Código de Establecimiento (SRI)')),
                ('codigo_punto_emision', models.CharField(max_length=3, verbose_name='Código de Punto de Emisión (SRI)')),
                ('secuencial_factura', models.PositiveIntegerField(default=1)),
                ('secuencial_nota_credito', models.PositiveIntegerField(default=1)),
                ('secuencial_retencion', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_venta', to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo_establecimiento', 'codigo_punto_emision')},
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.puntoventa'),
        ),
    ]
