# Generated by Django 5.2.5 on 2026-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio 1'),
        ),
        migrations.AlterUniqueTogether(
            name='productoprecio',
            unique_together={('producto', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoprecio',
            unique_together={('empresa', 'nombre')},
        ),
    ]
