# Generated by Django 5.2.5 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('empresa', 'marca', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['empresa', 'nombre'], name='core_catego_empresa_b729d8_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['empresa', 'nombre'], name='core_marca_empresa_9f0b43_idx'),
        ),
        migrations.AddIndex(
            model_name='modelo',
            index=models.Index(fields=['empresa', 'marca', 'nombre'], name='core_modelo_empresa_064e57_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'codigo'], name='core_produc_empresa_6e4f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'nombre'], name='core_produc_empresa_1e1f51_idx'),
        ),
    ]
