# Generated by Django 5.2.5 on 2026-03-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_habilitados', to='core.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulo')),
            ],
            options={
                'unique_together': {('empresa', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='PerfilModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_asignados', to='core.modulo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_asignados', to='core.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'modulo')},
            },
        ),
    ]
