# Generated by Django 5.2.5 on 2025-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_activo_categoria_producto_categoria_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('N', 'Anulada')], default='A', max_length=1),
        ),
    ]
