# Generated by Django 5.2.5 on 2025-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_factura_estado_pago_metodopago_factura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pagos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_con_impuestos',
            field=models.JSONField(default=dict),
        ),
    ]
