# Generated by Django 5.2.5 on 2025-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_factura_pagos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_sri',
            field=models.CharField(choices=[('P', 'Procesando'), ('A', 'Autorizada'), ('R', 'Rechazada'), ('C', 'Cancelada'), ('F', 'Firmado')], default='P', max_length=1),
        ),
    ]
