# Generated by Django 5.2.5 on 2025-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_factura_estado_sri'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='es_contado',
            field=models.BooleanField(default=True, help_text='Marcar si este método de pago se considera inmediato (Pagado).'),
        ),
    ]
