# Generated by Django 5.2.5 on 2025-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_metodopago_es_contado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sri_error',
            field=models.TextField(blank=True, help_text='Mensaje de error devuelto por el SRI, si lo hubiera.', null=True),
        ),
    ]
