# Generated by Django 5.2.5 on 2025-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_factura_sri_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='xml_firmado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
