# Generated by Django 5.2.5 on 2025-08-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_factura_xml_firmado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
