# Generated by Django 5.2.5 on 2025-10-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_proveedor_razon_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(verbose_name='Válida hasta')),
                ('estado', models.CharField(choices=[('B', 'Borrador'), ('E', 'Enviada'), ('A', 'Aceptada'), ('R', 'Rechazada'), ('V', 'Vencida'), ('F', 'Facturada')], default='B', max_length=1)),
                ('terminos_y_condiciones', models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones')),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_impuestos', models.JSONField(default=dict)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('factura_generada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='core.factura', verbose_name='Factura Generada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos', models.JSONField(default=dict)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
    ]
