# Generated by Django 5.2.5 on 2025-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cotizacion_cotizaciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Valor actual del IVA. Ej: 12.00 para 12%, 5.00 para 5%.', max_digits=5, verbose_name='Porcentaje de IVA (%)'),
        ),
    ]
