# Generated by Django 5.2.5 on 2025-10-09 18:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_empresa_iva_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total_con_impuestos',
            field=models.JSONField(default=dict, encoder=core.models.DecimalEncoder),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_con_impuestos',
            field=models.JSONField(default=dict, encoder=core.models.DecimalEncoder),
        ),
    ]
