# Generated by Django 5.2.5 on 2025-12-11 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cotizacion_total_con_impuestos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Chica Administración', max_length=100)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Custodio')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso / Reposición'), ('EGR', 'Egreso / Gasto')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(max_length=255, verbose_name='Descripción del gasto/ingreso')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/caja_chica/%Y/%m/', verbose_name='Evidencia/Recibo')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.cajachica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario_nombre', models.CharField(help_text='Nombre del beneficiario si no es cliente', max_length=200)),
                ('ruc_cedula', models.CharField(max_length=13, verbose_name='RUC/Cédula')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital Prestado')),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa Interés %')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('P', 'Pagado/Cerrado'), ('M', 'Mora/Vencido'), ('N', 'Anulado')], default='A', max_length=1)),
                ('saldo_capital_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_acumulado_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beneficiario_cliente', models.ForeignKey(blank=True, help_text='Si el beneficiario es un cliente registrado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AbonoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_capital', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto de este pago va a reducir la deuda original', max_digits=12)),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto de este pago es ganancia por intereses', max_digits=12)),
                ('codigo_deposito', models.CharField(blank=True, max_length=50, null=True, verbose_name='# Referencia Bancaria')),
                ('comprobante_deposito', models.FileField(blank=True, null=True, upload_to='comprobantes/prestamos/%Y/%m/', verbose_name='Comprobante de Depósito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.prestamo')),
            ],
        ),
    ]
