# Generated by Django 5.2.5 on 2025-12-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cajachica_movimientocaja_prestamo_abonoprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='plazo_meses',
            field=models.PositiveIntegerField(default=12, verbose_name='Plazo (Meses)'),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AH', 'Ahorros'), ('CTE', 'Corriente'), ('INV', 'Inversión / Plazo Fijo')], default='AH', max_length=3)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital', models.DecimalField(decimal_places=2, help_text='Parte que reduce la deuda', max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, help_text='Ganancia del banco', max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagada'), ('VEN', 'Vencida')], default='PEN', max_length=3)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('DEP', 'Depósito'), ('RET', 'Retiro')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=200)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.cuentabancaria')),
            ],
        ),
    ]
