# Generated by Django 5.2.5 on 2025-12-12 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_prestamo_plazo_meses_cuentabancaria_cuotaprestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Acceso (Home Banking)'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='impuestos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='precio_total_sin_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
