# Generated by Django 5.2.5 on 2026-01-16 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cliente_user_alter_facturadetalle_impuestos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='fecha_apertura',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='banco',
            field=models.CharField(default='Banco General', max_length=100, verbose_name='Nombre del Banco'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='color',
            field=models.CharField(default='#4e73df', max_length=7, verbose_name='Color de Tarjeta'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tipo',
            field=models.CharField(choices=[('AH', 'Ahorros'), ('CTE', 'Corriente')], max_length=3),
        ),
    ]
