# Generated by Django 5.2.5 on 2026-03-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_remove_cobro_estado_remove_cobro_porcentaje_and_more'),
        ('core', '0005_empresamodulo_perfilmodulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cobro',
            name='metodo_pago',
        ),
        migrations.CreateModel(
            name='CategoriaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_cobro', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Categoría de cobro',
                'verbose_name_plural': 'Categorías de cobro',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EstadoCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('total_documento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABONADO', 'Abonado'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_cuenta', to='cobros.categoriacobro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_cuenta_cobro', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta_cobro', to='core.empresa')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta_cobro', to='core.factura')),
            ],
            options={
                'verbose_name': 'Estado de cuenta por cobrar',
                'verbose_name_plural': 'Estados de cuenta por cobrar',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CARGO', 'Cargo inicial'), ('ABONO', 'Abono'), ('INTERES', 'Interés'), ('MORA', 'Mora'), ('DESCUENTO', 'Descuento'), ('AJUSTE_CARGO', 'Ajuste cargo'), ('AJUSTE_ABONO', 'Ajuste abono')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cobro', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cobro', to='core.empresa')),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cobros.estadocuentacobro')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cobro', to='core.factura')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de cobro',
                'verbose_name_plural': 'Movimientos de cobro',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_cobro', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_cobro', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo de cobranza',
                'verbose_name_plural': 'Préstamos de cobranza',
            },
        ),
        migrations.CreateModel(
            name='MovimientoPrestamoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('DESEMBOLSO', 'Desembolso'), ('CUOTA', 'Cuota'), ('ABONO_CAPITAL', 'Abono a capital'), ('INTERES', 'Interés'), ('MORA', 'Mora'), ('AJUSTE_CARGO', 'Ajuste cargo'), ('AJUSTE_ABONO', 'Ajuste abono')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_prestamo_cobro', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_prestamo_cobro', to='core.empresa')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cobros.prestamocobro')),
            ],
            options={
                'verbose_name': 'Movimiento de préstamo',
                'verbose_name_plural': 'Movimientos de préstamo',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromesaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_promesa', models.DateField()),
                ('monto_prometido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDA', 'Cumplida'), ('INCUMPLIDA', 'Incumplida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promesas_pago', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promesas_pago', to='core.empresa')),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promesas_pago', to='cobros.estadocuentacobro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promesa de pago',
                'verbose_name_plural': 'Promesas de pago',
            },
        ),
        migrations.DeleteModel(
            name='Abono',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cobro',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.AddIndex(
            model_name='estadocuentacobro',
            index=models.Index(fields=['empresa', 'cliente', 'estado'], name='cobros_esta_empresa_bb49f9_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocuentacobro',
            index=models.Index(fields=['empresa', 'fecha_vencimiento'], name='cobros_esta_empresa_fcc89c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocobro',
            index=models.Index(fields=['empresa', 'cliente', 'fecha'], name='cobros_movi_empresa_932a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocobro',
            index=models.Index(fields=['empresa', 'factura', 'tipo'], name='cobros_movi_empresa_3fc116_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamocobro',
            index=models.Index(fields=['empresa', 'cliente', 'estado'], name='cobros_pres_empresa_296928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prestamocobro',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AddIndex(
            model_name='movimientoprestamocobro',
            index=models.Index(fields=['empresa', 'cliente', 'fecha'], name='cobros_movi_empresa_75d43c_idx'),
        ),
        migrations.AddIndex(
            model_name='promesapago',
            index=models.Index(fields=['empresa', 'fecha_promesa', 'estado'], name='cobros_prom_empresa_c0a752_idx'),
        ),
    ]
