# Generated by Django 5.2.5 on 2026-03-18 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_remove_cobro_categoria_remove_cobro_cliente_and_more'),
        ('core', '0005_empresamodulo_perfilmodulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamocobro',
            name='cuota_estimada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prestamocobro',
            name='cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestamocobro',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamocobro',
            name='frecuencia_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='prestamocobro',
            name='tipo_interes',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('MENSUAL', 'Mensual')], default='SIMPLE', max_length=10),
        ),
        migrations.CreateModel(
            name='CompraFinanciada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_producto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuotas', models.PositiveIntegerField(default=1)),
                ('frecuencia_dias', models.PositiveIntegerField(default=30)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_financiadas', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_financiadas', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra financiada',
                'verbose_name_plural': 'Compras financiadas',
            },
        ),
        migrations.CreateModel(
            name='CuentaFinancieraCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('CAJA', 'Caja'), ('EFECTIVO', 'Efectivo'), ('BILLETERA', 'Billetera')], default='BANCO', max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('titular', models.CharField(blank=True, max_length=150, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_financieras_cobro', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta financiera',
                'verbose_name_plural': 'Cuentas financieras',
            },
        ),
        migrations.AddField(
            model_name='movimientoprestamocobro',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_prestamo', to='cobros.cuentafinancieracobro'),
        ),
        migrations.AddField(
            model_name='prestamocobro',
            name='cuenta_desembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_desembolsados', to='cobros.cuentafinancieracobro'),
        ),
        migrations.CreateModel(
            name='MovimientoCompraFinanciada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CARGO_INICIAL', 'Cargo inicial'), ('CUOTA', 'Cuota'), ('ABONO_EXTRA', 'Abono extra'), ('INTERES', 'Interés'), ('MORA', 'Mora'), ('AJUSTE_CARGO', 'Ajuste cargo'), ('AJUSTE_ABONO', 'Ajuste abono')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_compra_financiada', to='core.cliente')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cobros.comprafinanciada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_compra_financiada', to='core.empresa')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de compra financiada',
                'verbose_name_plural': 'Movimientos de compras financiadas',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRANSFERENCIA_ENTRADA', 'Transferencia entrada'), ('TRANSFERENCIA_SALIDA', 'Transferencia salida'), ('AJUSTE_MAS', 'Ajuste más'), ('AJUSTE_MENOS', 'Ajuste menos')], max_length=25)),
                ('origen', models.CharField(choices=[('PRESTAMO', 'Préstamo'), ('COMPRA_FINANCIADA', 'Compra financiada'), ('VENTA', 'Venta'), ('COBRO', 'Cobro'), ('OTRO', 'Otro')], default='OTRO', max_length=25)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cobros.cuentafinancieracobro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cuenta_cobro', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta',
                'verbose_name_plural': 'Movimientos de cuentas',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='comprafinanciada',
            index=models.Index(fields=['empresa', 'cliente', 'estado'], name='cobros_comp_empresa_d73bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='comprafinanciada',
            index=models.Index(fields=['empresa', 'fecha'], name='cobros_comp_empresa_618816_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comprafinanciada',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AddIndex(
            model_name='cuentafinancieracobro',
            index=models.Index(fields=['empresa', 'tipo', 'activo'], name='cobros_cuen_empresa_7867f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentafinancieracobro',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='movimientocomprafinanciada',
            index=models.Index(fields=['empresa', 'cliente', 'fecha'], name='cobros_movi_empresa_10f3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocuentacobro',
            index=models.Index(fields=['empresa', 'cuenta', 'fecha'], name='cobros_movi_empresa_14894f_idx'),
        ),
    ]
