# Generated by Django 5.2.5 on 2026-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_prestamocobro_cuota_estimada_prestamocobro_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamocobro',
            name='tipo_interes',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10),
        ),
    ]
